service: aws-new-api
frameworkVersion: '2 || 3'

custom:
  tableName: 'Employees'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ EmployeeTable, Arn ]
  environment:
    TABLENAME: ${self:custom.tableName}
    NODE_ENV: 'production'
    REGION: 'ap-south-1'

functions:
  employee-api:
    handler: handler.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    EmployeeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: LocationID
            AttributeType: S
          - AttributeName: Empcode
            AttributeType: S
        KeySchema:
          - AttributeName: LocationID
            KeyType: HASH
          - AttributeName: Empcode
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}
